services:
  db:
    image: postgres:15
    container_name: lms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: lms_web
    command: >
      sh -c "echo 'Waiting for database...' &&
             while ! nc -z db 5432; do sleep 1; done &&
             echo 'Database ready!' &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: